name: presentation
description: Presentation layer
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.3
  data:
    path: ../data

dev_dependencies:
  build_runner: ^2.1.7
  injectable_generator: ^1.5.3
  flutter_lints: ^1.0.0

assets:
  - assets/svg